version: "3.5"
services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./website:/var/www/learn.nginx
